version: 2
updates:
  - package-ecosystem: 'pip' # for Python packages
    directory: '/' # path to requirements.txt
    schedule:
      interval: 'daily' # adjust as needed
    commit-message:
      # Prefix all commit messages with "[Dependabot:PIP] "
      prefix: "[Dependabot:PIP] "

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      # Prefix all commit messages with ""[Dependabot:NPM]""
      prefix: ""[Dependabot:NPM]""