version: 2
updates:
  - package-ecosystem: 'pip' # for Python packages
    directory: '/' # path to requirements.txt
    schedule:
      interval: 'daily' # adjust as needed
    commit-message:
      # Prefix all commit messages with "pip: "
      prefix: "pip"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: "npm"

  - package-ecosystem: "docker" # for Dockerfile
    directory: "/dev"
    schedule:
      interval: "daily" # adjust as needed

  - package-ecosystem: "docker" # for Dockerfile
    directory: "/product"
    schedule:
      interval: "daily" # adjust as needed