version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/dev"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/product"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/dev"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/product"
    schedule:
      interval: "daily"